services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: member
      POSTGRES_USER: member
      POSTGRES_PASSWORD: member
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
