CREATE TABLE members
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            VARCHAR(255)  NOT NULL,
    name_encrypted   VARCHAR(2048) NOT NULL,
    phone_encrypted  VARCHAR(2048) NOT NULL,
    phone_hash       VARCHAR(64)   NULL,
    password_hash    VARCHAR(255)  NOT NULL,
    role             VARCHAR(20)   NOT NULL,
    status           VARCHAR(20)   NOT NULL,
    login_fail_count INT           NOT NULL DEFAULT 0,
    login_locked_until TIMESTAMPTZ NULL,
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL,
    withdrawn_at     TIMESTAMPTZ   NULL
);

ALTER TABLE members
    ADD CONSTRAINT uk_members_email UNIQUE (email);
ALTER TABLE members
    ADD CONSTRAINT uk_members_phone_hash UNIQUE (phone_hash);

CREATE INDEX idx_members_status ON members (status);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT      NOT NULL,
    jti        VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_refresh_tokens_jti UNIQUE (jti)
);

CREATE INDEX idx_refresh_tokens_member_id ON refresh_tokens (member_id);

CREATE TABLE admin_audit_logs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id         BIGINT       NOT NULL,
    target_member_id BIGINT,
    action           VARCHAR(50)  NOT NULL,
    result           VARCHAR(20)  NOT NULL,
    ip_address       VARCHAR(45)  NOT NULL,
    request_uri      VARCHAR(255) NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_audit_admin_id    ON admin_audit_logs (admin_id);
CREATE INDEX idx_audit_accessed_at ON admin_audit_logs (created_at);
